kernel/hwmon-max6697: 6.12: fix missing dependency
Add missing depends kmod-regmap-i2c.

ERROR: modpost: "__regmap_init_i2c" [drivers/hwmon/max6697.ko] undefined!

Signed-off-by: Mieczyslaw Nalewaj <namiltd@yahoo.com>